# Generated by Django 3.2.16 on 2025-01-13 03:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gestion_de_carros', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Taller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idn', models.CharField(max_length=50, verbose_name='Id*')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre*')),
                ('direccion', models.CharField(max_length=50, verbose_name='Direccion*')),
                ('telefono', models.IntegerField(verbose_name='Telefono*')),
                ('especializacion', models.CharField(max_length=50, verbose_name='Especializacion*')),
            ],
            options={
                'permissions': (('crear_taller', 'Puede Crear Un Taller'), ('vista_taller', 'Puede Consultar Taller'), ('actualizar_taller', 'Puede Actualizar datos del Taller'), ('eliminar_taller', 'Puede Eliminar un Taller')),
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='Mantenimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idn', models.CharField(max_length=50, verbose_name='Identificacion*')),
                ('fecha', models.DateTimeField(verbose_name='Fecha*')),
                ('tipo_servicio', models.CharField(max_length=50, verbose_name='Tipo servicio*')),
                ('costo', models.IntegerField(verbose_name='Costo*')),
                ('descripcion', models.TextField(verbose_name='Descripcion*')),
                ('estado', models.BooleanField(default=True, verbose_name='¿Activo?')),
                ('id_taller', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestion_de_taller.taller', verbose_name='Id Taller*')),
                ('placa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestion_de_carros.carro', verbose_name='Placa*')),
            ],
            options={
                'permissions': (('crear_mantenimiento', 'Puede Crear Mantenimiento'), ('vista_mantenimiento', 'Puede Consultar Mantenimiento'), ('actualizar_mantenimiento', 'Puede Actualizar Mantenimiento'), ('eliminar_mantenimiento', 'Puede Eliminar Mantenimiento')),
                'default_permissions': (),
            },
        ),
    ]
