# Generated by Django 3.2.16 on 2025-01-26 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_de_taller', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taller',
            name='telefono',
            field=models.CharField(max_length=20, verbose_name='Telefono*'),
        ),
    ]
