# Generated by Django 3.2.16 on 2025-01-29 15:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gestion_de_carros', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Multas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni', models.CharField(max_length=50, verbose_name='Id*')),
                ('fecha', models.DateTimeField(verbose_name='Fecha*')),
                ('infraccion', models.CharField(max_length=50, verbose_name='Infraccion*')),
                ('monto', models.PositiveIntegerField(verbose_name='Monto*')),
                ('estado', models.BooleanField(default=True, verbose_name='¿Activo?')),
                ('placa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestion_de_carros.carro', verbose_name='Placa*')),
            ],
            options={
                'permissions': (('crear_multa', 'Puede Crear Multas'), ('ver_multa', 'Puede Consultar Multas'), ('actualizar_multa', 'Puede Actualizar Multa'), ('eliminar_multa', 'Puede Eliminar Multa')),
                'default_permissions': (),
            },
        ),
    ]
