# Generated by Django 3.2.16 on 2025-02-03 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gestion_de_carros', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aseguradora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_aseguradora', models.CharField(max_length=50, verbose_name='Id*')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre*')),
                ('direccion', models.CharField(max_length=50, verbose_name='Direccion*')),
                ('telefono', models.CharField(max_length=50, verbose_name='Telefono*')),
                ('email', models.EmailField(max_length=50, verbose_name='Email*')),
            ],
            options={
                'permissions': (('crear_aseguradora', 'Puede Crear Una Aseguradora'), ('vista_aseguradora', 'Puede Consultar Aseguradora'), ('actualizar_aseguradora', 'Puede Actualizar una Aseguradora'), ('eliminar_aseguradora', 'Puede Eliminar una Aseguradora')),
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='Seguro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni', models.CharField(max_length=50, verbose_name='Identificacion*')),
                ('fecha_inicio', models.DateTimeField(verbose_name='Fecha Inicio*')),
                ('fecha_fin', models.DateTimeField(verbose_name='Fecha Fin*')),
                ('costo', models.CharField(max_length=50, verbose_name='Costo*')),
                ('tipo_cobertura', models.IntegerField(verbose_name='Cobertura*')),
                ('estado', models.BooleanField(default=True, verbose_name='¿Activo?')),
                ('id_aseguradora', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestion_de_seguros.aseguradora', verbose_name='Id aseguradora*')),
                ('placa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestion_de_carros.carro', verbose_name='Placa*')),
            ],
            options={
                'permissions': (('crear_seguro', 'Puede Crear Seguro'), ('vista_seguro', 'Puede Consultar Seguro'), ('actualizar_seguro', 'Puede Actualizar Seguro'), ('eliminar_seguro', 'Puede Eliminar Seguro')),
                'default_permissions': (),
            },
        ),
    ]
