# Generated by Django 3.2.16 on 2025-01-26 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_de_seguros', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aseguradora',
            name='telefono',
            field=models.CharField(max_length=50, verbose_name='Telefono*'),
        ),
    ]
