# Generated by Django 3.2.16 on 2025-01-08 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(choices=[('TOYOTA', 'Toyota'), ('FORD', 'Ford'), ('CHEVROLET', 'Chevrolet'), ('NISSAN', 'Nissan'), ('BMW', 'Bmw')], max_length=50, verbose_name='Marca*')),
                ('modelo', models.CharField(max_length=50, verbose_name='Modelo*')),
                ('anio', models.DateTimeField(verbose_name='Fecha de creacion*')),
                ('precio', models.IntegerField(verbose_name='Precio del carro*')),
                ('disponible', models.BooleanField(default=True, verbose_name='¿Disponible?')),
            ],
            options={
                'permissions': (('crear_carro', 'Puede Crear Carros'), ('consultar_carros', 'Puede Consultar Carros'), ('editar_carros', 'Puede Editar Carros'), ('eliminar_carros', 'Puede Eliminar Carros')),
                'default_permissions': (),
            },
        ),
    ]
