# Generated by Django 3.2.16 on 2025-01-12 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(blank=True, max_length=50, null=True, verbose_name='Placa*')),
                ('marca', models.CharField(choices=[('TOYOTA', 'Toyota'), ('FORD', 'Ford'), ('CHEVROLET', 'Chevrolet'), ('NISSAN', 'Nissan'), ('BMW', 'Bmw')], max_length=50, verbose_name='Marca*')),
                ('modelo', models.CharField(max_length=50, verbose_name='Modelo*')),
                ('anio', models.DateTimeField(verbose_name='Fecha de creacion*')),
                ('color', models.CharField(blank=True, max_length=50, null=True, verbose_name='Color*')),
                ('tipo', models.CharField(blank=True, choices=[('PRIVADO', 'Privado'), ('PUBLICO', 'Publico')], max_length=50, null=True, verbose_name='Tipo*')),
                ('precio', models.IntegerField(verbose_name='Precio del carro*')),
                ('kilometraje', models.FloatField(blank=True, max_length=50, null=True, verbose_name='Kilometraje*')),
                ('disponible', models.BooleanField(default=True, verbose_name='¿Disponible?')),
            ],
            options={
                'permissions': (('crear_carro', 'Puede Crear Carro'), ('ver_carro', 'Puede Consultar Carro'), ('actualizar_carros', 'Puede Actualizar Carro'), ('eliminar_carro', 'Puede Eliminar Carro')),
                'default_permissions': (),
            },
        ),
    ]
