# Generated by Django 3.2.16 on 2025-01-09 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_de_carros', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carro',
            name='placa',
            field=models.IntegerField(blank=True, null=True, verbose_name='Placa*'),
        ),
    ]
