# Generated by Django 3.2.16 on 2025-01-09 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_de_carros', '0002_alter_carro_placa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carro',
            name='placa',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Placa*'),
        ),
    ]
