# Generated by Django 3.2.16 on 2025-01-09 22:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gestion_de_carros', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Propietario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni', models.CharField(max_length=50, verbose_name='Identificacion*')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre*')),
                ('apellido', models.CharField(max_length=50, verbose_name='Apellido*')),
                ('direccion', models.CharField(max_length=50, verbose_name='Direccion*')),
                ('telefono', models.IntegerField(verbose_name='Telefono*')),
                ('email', models.EmailField(max_length=50, verbose_name='Email*')),
                ('placa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestion_de_carros.carro', verbose_name='Placa*')),
            ],
            options={
                'permissions': (('crear_carro', 'Puede Crear Carros'), ('consultar_carros', 'Puede Consultar Carros'), ('editar_carros', 'Puede Editar Carros'), ('eliminar_carros', 'Puede Eliminar Carros')),
                'default_permissions': (),
            },
        ),
    ]
