# Generated by Django 3.2.16 on 2025-02-03 18:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gestion_de_carros', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Propietario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni', models.CharField(max_length=50, verbose_name='Identificacion*')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre*')),
                ('apellido', models.CharField(max_length=50, verbose_name='Apellido*')),
                ('direccion', models.CharField(max_length=50, verbose_name='Direccion*')),
                ('telefono', models.CharField(max_length=20, verbose_name='Telefono*')),
                ('email', models.EmailField(max_length=50, verbose_name='Email*')),
                ('placa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestion_de_carros.carro', verbose_name='Placa*')),
            ],
            options={
                'permissions': (('crear_propietario', 'Puede Crear Propietarios'), ('vista_propietario', 'Puede Consultar Propietarios'), ('actualizar_propietario', 'Puede Actualizar Propietarios'), ('eliminar_propietario', 'Puede Eliminar Propietarios')),
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='Licencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=50, verbose_name='N.Licencia*')),
                ('tipo', models.CharField(choices=[('PRIVADO', 'Privado'), ('PUBLICO', 'Publico')], max_length=50, verbose_name='Tipo*')),
                ('fecha_emision', models.DateTimeField(verbose_name='Fecha de emision*')),
                ('fecha_vencimiento', models.DateTimeField(verbose_name='Fecha de vencimiento*')),
                ('estado', models.BooleanField(default=True, verbose_name='¿Activo?')),
                ('dni', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestion_de_propietarios.propietario', verbose_name='Identificacion*')),
            ],
            options={
                'permissions': (('crear_licencia', 'Puede Crear licencia'), ('ver_licencia', 'Puede Consultar Licencias'), ('actualizar_licencia', 'Puede Actualizar Licencia'), ('eliminar_licencia', 'Puede Eliminar Licencia')),
                'default_permissions': (),
            },
        ),
    ]
