# Generated by Django 3.2.16 on 2025-01-25 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_de_propietarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propietario',
            name='telefono',
            field=models.CharField(max_length=20, verbose_name='Telefono*'),
        ),
    ]
